spring:
  application:
    name: admin-server
server:
  port: 8769
eureka:
  client:
    service-url:
      defautZone: http://${MY_IP}:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS