server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.128.15.113:8761/eureka/

spring:
  application:
    name: emergency-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c4mvhuxgrca9.ap-southeast-1.rds.amazonaws.com:3306/ridehailing
    username: admin
    password: 624730152myh



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.qq.com
    username: 436096861@qq.com
    password: wypcthhdhqnzbgig
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
#  rabbitmq:
#    host: 47.115.33.176
#    port: 5672
#    username: guest
#    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

