server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://rm-bp12upfcvvr173aq0uo.mysql.rds.aliyuncs.com:3306/ridehailing?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
#    username: ridehailing01
#    password: Hx123456


    url: jdbc:mysql://database-2.c4mvhuxgrca9.ap-southeast-1.rds.amazonaws.com:3306
    username: admin
    password: 624730152myh


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.qq.com
    username: 436096861@qq.com
    password: wypcthhdhqnzbgig
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
  rabbitmq:
    host: 47.115.33.176
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

