server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.31.43.41:8761/eureka/
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c4mvhuxgrca9.ap-southeast-1.rds.amazonaws.com:3306/ridehailing
    username: admin
    password: 624730152myh



mybatis:
  type-aliases-package: com.example.oderservice.pojo
  mapper-locations: classpath:mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS