server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: 172.31.43.41
  server:
    # 关闭保护机制，默认true
    enable-self-preservation: false
    # 剔除失效服务间隔，默认60000(毫秒)
    eviction-interval-timer-in-ms: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://47.128.15.113:8761

